# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cb414eb4f8885ddadae4eb74e2f9b15b78f03eade17d638c0477b4b85c3b01b8bfd6ddc48f1a1a94e253587d50c2eda498a245489a1e3a280b54cd3ed78e5ef

test:
  secret_key_base: 6fa0dec1d0ed9e57ae57dc5f57b1a01ad4dc4b50cd28efc4be4912f0a99ff4fb5385e08553d3c870c6fb533fd4c5fcd3b428500c5a9ca74b255dc4319b296de6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
